### ISSUE TITLE
Rails Recipe: Setup the Kanban board

### ISSUE THREAD

**Issue by mahdinoori2000** [mahdinoori2000/rails-group-capstone#12]
### What is added

**Github Kanbanborad link:** https://github.com/mahdinoori2000/rails-group-capstone/projects/1

We are 2 people in our team:

- **Mahdi Noori:** @mahdinoori2000 
- **Richard Sikaonga:** @richie1988

**Comment by julie-ify** [comment]
## Hi @mahdinoori2000 and @richie1988,

Good job so far!

## Highlights!
- Descriptive issues ✔️ 

Hello ✋, you have done well reaching this point of the milestone 🤝 . But there are some issues that you still need to work on to go to the next project but you are almost there!

# Status: Required Changes ♻️⛔️
- [ ] Kindly ensure this task has the required description. This task's description varies from the one in the guideline.

  ![image](https://github.com/mahdinoori2000/rails-group-capstone/assets/81468675/179eb293-9a1c-4aee-8764-415c8cf093b3)

  ![image](https://github.com/mahdinoori2000/rails-group-capstone/assets/81468675/47437374-0c03-4b6f-b3e1-6cee16e9473d)

- [ ] The points difference between team members should not exceed 4 points. Kindly distribute your tasks evenly. @mahdinoori2000 has points totaling 18 points, while @richie1988 has only 11 points.


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread and tag me `@julie-ify` if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by julie-ify** [comment]
Hi @mahdinoori2000 and @richie1988,

## Highlights!
- Descriptive issue ✔️

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

# Status: Approved ✔️ 

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
